name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PHP application image
        run: docker build -t docker-practice-php-web .  # Replace '.' with your Dockerfile path if different

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag PHP application image
        run: docker tag docker-practice-php-web:latest "${{ secrets.DOCKERHUB_USERNAME }}/php-web:latest"

      - name: Push PHP application image (Optional check)
        run: |
          docker images | grep docker-practice-php-web:latest && docker push "${{ secrets.DOCKERHUB_USERNAME }}/php-web:latest"


      # - name: Build Docker container
      #   run: docker compose up -d

      - name: Show images
        run: docker images  

      # - name: Log into Docker Hub
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # - name: Tag php-web image
      #   run: docker tag docker-practice-php-web:latest "${{ secrets.DOCKERHUB_USERNAME }}/php-web:latest"

      # - name: Push php-web image to Docker Hub
      #   run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/php-web:latest"

      # - name: Tag mysql image
      #   run: docker tag mysql:latest "${{ secrets.DOCKERHUB_USERNAME }}/php-mysql:latest"

      # - name: Push mysql image to Docker Hub
      #   run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/php-mysql:latest"
